# Generated by Django 5.2.6 on 2025-09-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_password_changed',
            field=models.BooleanField(default=False, help_text='첫 로그인 시 비밀번호 변경 여부'),
        ),
    ]
