# Generated by Django 5.2.4 on 2025-09-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0002_userprofile_is_password_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionrecord',
            name='diet_target',
            field=models.JSONField(blank=True, default=dict, help_text='식단 권고사항 (Target 객체)', null=True),
        ),
    ]
