# Generated by Django 5.2.4 on 2025-09-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0003_alter_interventionrecord_diet_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interventionrecord',
            name='exercise_target',
            field=models.IntegerField(blank=True, help_text='운동 목표 걸음 수', null=True),
        ),
    ]
