# Generated by Django 5.2.4 on 2025-09-23 10:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0005_alter_interventionrecord_sleep_evaluation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interventionrecord',
            unique_together={('user', 'target_date')},
        ),
    ]
