# Generated by Django 5.2.4 on 2025-09-23 10:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0006_alter_interventionrecord_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='interventionrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='interventionrecord',
            name='gubun',
            field=models.CharField(choices=[('all', '전체 (음식, 운동)'), ('sleep', '수면')], default='all', help_text='중재 구분', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='interventionrecord',
            unique_together={('user', 'record_date', 'gubun')},
        ),
    ]
