# Generated by Django 5.2.4 on 2025-09-24 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0007_alter_interventionrecord_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10, verbose_name='플랫폼')),
                ('version', models.CharField(help_text='예: 0.1.11+11', max_length=20, verbose_name='최소 지원 버전')),
                ('download_url', models.URLField(max_length=500, verbose_name='다운로드 URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '시스템 프로필',
                'verbose_name_plural': '시스템 프로필들',
                'ordering': ['-created_at'],
                'unique_together': {('platform',)},
            },
        ),
    ]
