# Generated by Django 5.2.4 on 2025-09-24 03:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0008_systemprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=10, verbose_name='플랫폼')),
                ('app_version', models.CharField(help_text='예: 0.1.11+11', max_length=20, verbose_name='앱 버전')),
                ('login_type', models.CharField(choices=[('auto', '자동 로그인'), ('manual', '수동 로그인'), ('social', '소셜 로그인')], max_length=10, verbose_name='로그인 타입')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP 주소')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('device_info', models.JSONField(blank=True, default=dict, null=True, verbose_name='디바이스 정보')),
                ('login_time', models.DateTimeField(auto_now_add=True, verbose_name='로그인 시간')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 로그인 이력',
                'verbose_name_plural': '사용자 로그인 이력들',
                'ordering': ['-login_time'],
                'indexes': [models.Index(fields=['user', 'login_time'], name='ibsafe_user_user_id_166758_idx'), models.Index(fields=['platform'], name='ibsafe_user_platfor_96a4e4_idx'), models.Index(fields=['login_type'], name='ibsafe_user_login_t_c03844_idx')],
            },
        ),
    ]
