# Generated by Django 5.2.4 on 2025-09-24 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0009_userloginhistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterventionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gubun', models.CharField(choices=[('food', '음식 기록'), ('sleep', '수면 기록'), ('exercise', '운동 기록'), ('medication', '복용약 기록'), ('survey', '설문 기록')], help_text='작업 유형', max_length=20, verbose_name='구분')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간')),
                ('processing_time', models.FloatField(help_text='end_time - start_time', verbose_name='처리 시간 (초)')),
                ('record_date', models.DateField(help_text='작업 대상 날짜', verbose_name='기록 날짜')),
                ('success', models.BooleanField(default=True, verbose_name='성공 여부')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intervention_stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '중재 통계',
                'verbose_name_plural': '중재 통계들',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'gubun'], name='ibsafe_inte_user_id_d08ffb_idx'), models.Index(fields=['record_date'], name='ibsafe_inte_record__4c8dfb_idx'), models.Index(fields=['start_time'], name='ibsafe_inte_start_t_bd58f0_idx')],
            },
        ),
    ]
