# Generated by Django 5.2.4 on 2025-09-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0011_interventionrecord_food_evaluation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interventionrecord',
            name='input_fodmap_count',
            field=models.JSONField(blank=True, default=dict, help_text='포드맵 음식 수 (전체, 저포드맵, 고포드맵 수)', null=True),
        ),
    ]
