# Generated by Django 5.2.4 on 2025-09-24 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0012_interventionrecord_input_fodmap_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationschedule',
            name='gubun',
            field=models.CharField(choices=[('notification', '알림'), ('exercise_save', '운동저장')], default='notification', help_text='알림 또는 액션', max_length=20, verbose_name='구분'),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='body',
            field=models.TextField(blank=True, help_text='알림인 경우에만 사용', verbose_name='알림 내용'),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='description',
            field=models.TextField(blank=True, verbose_name='스케줄 설명'),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='name',
            field=models.CharField(max_length=100, verbose_name='스케줄 이름'),
        ),
        migrations.AlterField(
            model_name='notificationschedule',
            name='title',
            field=models.CharField(blank=True, help_text='알림인 경우에만 사용', max_length=200, verbose_name='알림 제목'),
        ),
        migrations.CreateModel(
            name='UserExerciseHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField(help_text='기록 날짜')),
                ('record_time', models.TimeField(help_text='기록 시간')),
                ('target_steps', models.IntegerField(help_text='목표 걸음 수')),
                ('current_steps', models.IntegerField(help_text='현재 걸음 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercise_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '사용자 운동 히스토리',
                'verbose_name_plural': '사용자 운동 히스토리들',
                'ordering': ['-record_date', '-record_time'],
                'indexes': [models.Index(fields=['user', 'record_date'], name='ibsafe_user_user_id_6ac96f_idx'), models.Index(fields=['record_date', 'record_time'], name='ibsafe_user_record__3c40c5_idx')],
                'unique_together': {('user', 'record_date', 'record_time')},
            },
        ),
    ]
