# Generated by Django 5.2.4 on 2025-09-25 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ibsafe', '0013_notificationschedule_gubun_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationschedule',
            name='send_notification',
            field=models.BooleanField(default=True, help_text='True이면 알림 메시지 발송, False이면 알림 메시지 발송 안함', verbose_name='알림 발송 여부'),
        ),
    ]
